### PR TITLE
Code generation

### PR DESCRIPTION
**Pull request by oddgfa**
Merged Decl, Expr and Stmt branches into this one. Currently able to generate code and run the following program:
```
program CompilaCmp
begin
  class Complex
    begin
        var Real : float;
        var Imag : float;
    end;
  var dummy : Complex;

  proc Add(x : int, y : int): int
  begin
    var i : int;
    var j : float;
    var lit : bool;
    i := 5;
    while (i > 0) do
      begin
      i := i - 1;
      end;
    i := i + 10;
    i := i - 1;
    i := i * 2;
    i := i / 2;
    //j := 1.0 # 2.0;
    lit := true;
    if (lit) then
      begin
      i := 0;
      end
    else
      begin
      i := 1;
      end;
    return i + y;
  end;

  proc Main()
  begin
    printint(Add(1, 2));
    return;
  end;
end;
```

As it is now it will list the generated bytecode and then run it as I still haven't managed to run the virtual machine from my terminal.

### CODE REVIEW

**Comment by saliha-sajid** [comment]
@oddgfa which command do you use for running VM?

**Comment by oddgfa** [comment]
Currently i don't use any. Doing `ant run` will compile the contents of `Compila.cmp`, generate byte code, print the generated byte code as a list of commands and then run it. Can't get the VM to work from the terminal.

**Comment by saliha-sajid** [comment]
It worked fine on my computer.

**Comment by saliha-sajid** [comment]
I reverted the merge of Stmt with master branch. ant test stops after test 8.

**Pull request merged**
